{1,
{2,
{"ШаблоныПодписей",1,0,"",""},
{0,
{"Подпись",0,0,"ё","//++ <?""Номер задачи""> <?"""", ДатаВремя, ""ДФ=dd.MM.yyyy""> daniil.vasilev@innostage-group.ru

//-- <?""Номер задачи""> <?"""", ДатаВремя, ""ДФ=dd.MM.yyyy""> daniil.vasilev@innostage-group.ru  "}
},
{0,
{"Подпись одинарная",0,0,"ё","// <?""Номер задачи""> <?"""", ДатаВремя, ""ДФ=dd.MM.yyyy""> daniil.vasilev@innostage-group.ru
"}
}
}
}